### PR TITLE
Better performance with Postgres

### PR DESCRIPTION
**Pull request by giovannibonetti**
At least in my machine, this patch made a dramatic speed-up to the conversion (more than 10x)

### CODE REVIEW

**Comment by patrickemuller** [comment]
@giovannibonetti can you do this Patch on original gem? Apparently this one isn't maintained anymore...

**Comment by giovannibonetti** [comment]
Hi, @patrickemuller! What do you mean by that? I don't have authorization to update this library on Rubygems.

**Comment by giovannibonetti** [comment]
Woops, my mistake, I had done the PR in the wrong repo. Here it is, now: https://github.com/girishso/pluck_to_hash/pull/21

**Comment by patrickemuller** [comment]
@giovannibonetti nice man! thanks for that ;)

**Pull request merged**
